name: feature_ssh_key_manager

environment:
  sdk: ^3.9.2
  flutter:

dependencies:
  flutter:
    sdk: flutter

  provider:
  path:
  lucide_icons_flutter:
  domain:
    path: ../../../domain
  ui:
    path: ../../../ui
  util:
    path: ../../../util
  shared:
    path: ../../../shared

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

resolution:
  workspace

flutter:
